changelog:
  categories:
    - title: 🏕 Features
      labels:
        - 'feature'
    - title: 👒 Dependencies
      labels:
        - deps
    - title: 🐛 Bug Fixes
      labels:
        - fix
    - title: 📝 Documentation
      labels:
        - docs
