apiVersion: v1
kind: Namespace
metadata:
  name: test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name ngx-1
  namespace: test-1
spec:
  replicas: 5
  selector:
    matchLabels: &matchLabels
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels: *matchLabels
    spec:
      containers:
      - name: *name
        image: nginx:alpine
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name ngx-1
  namespace: test-2
spec:
  replicas: 5
  selector:
    matchLabels: &matchLabels
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels: *matchLabels
    spec:
      containers:
      - name: *name
        image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name ngx-2
  namespace: test-2
spec:
  replicas: 5
  selector:
    matchLabels: &matchLabels
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels: *matchLabels
    spec:
      containers:
      - name: *name
        image: nginx:alpine
