name: tests

on:
  push:
    branches:
      - "**"

jobs:
  vetting:
    name: vetting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v5
      - name: go mod tidy
        run: go mod tidy
      - name: vetting
        shell: bash
        run: go vet ./...

  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v5
      - name: go mod tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m --issues-exit-code=1 ./...
          only-new-issues: true

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    needs:
      - vetting
      - linting
    env:
      LOG_DIR: logs
      FORMATTED_LOG_FOLDER_NAME: ""
    steps:
      - uses: actions/setup-go@v5
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go mod tidy
        run: go mod tidy
      - name: Run unit tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
